# Generated by Django 2.2.1 on 2020-03-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicfile', models.FileField(null=True, upload_to='storage')),
            ],
        ),
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=0)),
                ('file', models.FileField(null=True, upload_to='music')),
            ],
        ),
    ]
